### ISSUE TITLE
probs with interpolation in attributes

### ISSUE THREAD

**Issue by tribalvibes** [creationix/haml-js#41]
Thanks for putting this together--perfect timing for us :)

I'm trying to find the easiest way to conditionally include an attribute, and running into the following. E.g.,:

```
    - var target = thumbnail_url ? "target=\\"_blank\\"" : null
    %a( href="#{id}" #{target} )= name
```

This seems really awkward and so I am thinking of hacking the attribute parser to add some sort of conditional interpolation. Any thoughts on this?   But, unfortunately, even the above does not work as expected and instead produces:

```
   var _$output="";var target = thumbnail_url ? "target=\"_blank\"" : null; _$output = _$output  +
"<a href=\"" +
html_escape(id) +
"\">" + 
name + 
"</a>";
```

which clearly (note the lack of interpolation of #{target} and the dangling quote ") seems like a bug, no?

Thanks!
tv/

**Comment by skatenerd** [comment]
FWIW, I stumbled across this issue and reading it saved me a lot of time.
