### ISSUE TITLE
Indentation problem

### ISSUE THREAD

**Issue by Preen** [creationix/haml-js#85]
Hi
When using indentation instead of white space:

!!! XML
!!!
%html
--%head
--%body'

This results in:
<?xml version='1.0' encoding='utf-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html></html><head></head><body></body>

**Comment by SandHilt** [comment]
try 2 spaces.
