### ISSUE TITLE
Error behavior inconsistent

### ISSUE THREAD

**Issue by StoneCypher** [creationix/haml-js#89]
The error behavior in #74 and #88 seems to be inconsistent.  In the former case, the haml tool fails in a way that the gulp wrapper aborts, which is the appropriate behavior.  In the latter case, however, a large HTML error message is written to file, and the task appears to succeed.

**Comment by raulsann** [comment]
+1.

The execute function needs a more advanced error handling: 
https://github.com/creationix/haml-js/blob/master/lib/haml.js#L650

It would be useful to have 2 options in the case of an error:

1) throw an error when it fails.
or
2) ignore it but log it.

**Comment by aaronblohowiak** [comment]
Pull requests accepted to add the option.

**Comment by StoneCypher** [comment]
@seballot - since you just fixed #88, could you look at this too?
